@echo off
setlocal enabledelayedexpansion

REM ============================================================
REM DataOps Studio - Enable Production Mode
REM
REM What this does:
REM   1. Generate a random JWT secret via portable Python
REM   2. Write .env with DATAOPS_ENV=prod + DATAOPS_JWT_SECRET=<secret>
REM   3. If config\config.yml doesn't exist, copy from .example as template
REM   4. Open .env in notepad so you can review (Ctrl+S to save)
REM   5. Print restart instruction
REM
REM Usage:
REM   enable-prod.bat                 (current dir = install root)
REM   enable-prod.bat D:\DataOpsStudio
REM
REM Re-running detects existing prod .env and asks before rotating secret.
REM ============================================================

set "APP_DIR=%~1"
if "%APP_DIR%"=="" set "APP_DIR=%cd%"
set "APP_DIR=!APP_DIR:"=!"
if "!APP_DIR:~-1!"=="\" set "APP_DIR=!APP_DIR:~0,-1!"

if not exist "!APP_DIR!\main.py" (
  echo [ERROR] "!APP_DIR!\main.py" not found.
  echo         Run from DataOpsStudio root or pass it as argument.
  pause
  exit /b 1
)
if not exist "!APP_DIR!\start.bat" (
  echo [ERROR] start.bat missing - did you run update.bat first?
  pause
  exit /b 1
)

REM ---- Find Python ----
set "PYEXE="
if exist "!APP_DIR!\python\python.exe"        set "PYEXE=!APP_DIR!\python\python.exe"
if not defined PYEXE if exist "!APP_DIR!\.venv\Scripts\python.exe" set "PYEXE=!APP_DIR!\.venv\Scripts\python.exe"
if not defined PYEXE (
  echo [ERROR] No Python found in !APP_DIR!\python\ or !APP_DIR!\.venv\
  echo         Cannot generate JWT secret without Python.
  pause
  exit /b 1
)

REM ---- Detect existing prod .env ----
set "ENV_FILE=!APP_DIR!\.env"
set "ALREADY_PROD=0"
if exist "!ENV_FILE!" (
  findstr /B /C:"DATAOPS_ENV=prod" "!ENV_FILE!" >nul 2>nul
  if not errorlevel 1 set "ALREADY_PROD=1"
)
if "!ALREADY_PROD!"=="1" (
  echo.
  echo .env already enables PROD mode. Rotating JWT secret will log out
  echo ALL existing users (they need to re-login). Continue?
  echo.
  set /p "CONFIRM=Type YES to rotate secret, anything else to abort: "
  if /i not "!CONFIRM!"=="YES" (
    echo Aborted. No changes made.
    pause
    exit /b 0
  )
  REM Backup existing .env before overwriting
  copy /Y "!ENV_FILE!" "!ENV_FILE!.bak" >nul
  echo Backed up existing .env to .env.bak
)

echo.
echo ============================================
echo  Enable PROD mode for DataOps Studio
echo  Dir : !APP_DIR!
echo ============================================
echo.

REM ---- Generate JWT secret ----
echo [1/5] Generating random JWT secret...
for /f "delims=" %%S in ('"!PYEXE!" -c "import secrets; print(secrets.token_urlsafe(64))"') do set "JWT_SECRET=%%S"
if not defined JWT_SECRET (
  echo [ERROR] Failed to generate secret. Check Python install.
  pause
  exit /b 1
)
echo   OK (secret length: 86 chars, not displayed for safety^).

REM ---- Write .env ----
echo.
echo [2/5] Writing .env...
> "!ENV_FILE!" (
  echo # DataOps Studio production mode
  echo # Generated by enable-prod.bat at !date! !time!
  echo # Do NOT commit this file to git. Do NOT share the secret.
  echo DATAOPS_ENV=prod
  echo DATAOPS_JWT_SECRET=!JWT_SECRET!
)
echo   OK: !ENV_FILE!

REM ---- Copy config.yml template if not present ----
echo.
echo [3/5] Ensuring config\config.yml.example exists...
if not exist "!APP_DIR!\config" mkdir "!APP_DIR!\config" >nul
if not exist "!APP_DIR!\config\config.yml.example" (
  if exist "%~dp0config.yml.example" copy /Y "%~dp0config.yml.example" "!APP_DIR!\config\config.yml.example" >nul
)
if exist "!APP_DIR!\config\config.yml.example" (
  echo   OK: config\config.yml.example available (copy to config.yml if you want to tune thresholds^)
) else (
  echo   Skipped: config.yml.example not found in upgrade package.
)

REM ---- Open .env in notepad for review ----
echo.
echo [4/5] Opening .env in notepad for review...
echo   ^(close notepad to continue^)
notepad "!ENV_FILE!"

REM ---- Verify by restarting + curl ----
echo.
echo [5/5] Verification:
echo.
echo  PROD mode is now configured. Next steps:
echo.
echo    1. Close the running app if any (close start.bat window or Ctrl+C)
echo    2. Double-click start.bat to restart
echo    3. Check the new uvicorn log under logs\
echo       Should NOT see "DATAOPS_JWT_SECRET unconfigured" warning anymore.
echo.
echo    4. Open http://localhost:8010 in browser. All previous user sessions
echo       are now INVALID (signed with old dev key). Everyone must re-login.
echo.
echo  To go back to dev mode:  run disable-prod.bat
echo  To rotate the secret:    run enable-prod.bat again (will prompt)
echo ============================================
pause
endlocal
